# output_dir: outputs/baseline_pack_wrapped_128_lr_1e-4_bertmask
output_dir: outputs/32k_baseline_pack_wrapped_lr_1e-4_100M/baseline_pack_wrapped_256_lr_1e-4_bertmask_100M
seed: 42
mode: baseline

tokenizer_path: tokenizers/tokenizer_100M_32k.json

data_args:
  use_packing: true
  packing_strategy: wrapped
  objective: mlm
  insert_eos: false
  train_path: data/processed_100M/vocab_32k/Baseline_Naive/train
  val_path: data/global_validation

model_args:
  model_type: bert
  hidden_size: 256
  num_hidden_layers: 4
  num_attention_heads: 4
  intermediate_size: 1024
  max_position_embeddings: 512
  pad_token_id: 3

training_args:
  batch_size: 4
  max_length: 256
  mlm_probability: 0.15
  learning_rate: 0.0001
  max_epochs: 1
  max_steps: 
  eval_every_steps: 1000
  max_val_steps: 20
  max_adjusted_token_exposure: 100000000
  checkpoint_interval_tokens: 10000000